require("__wayward-seas__/prototypes/plantables")
require("__wayward-seas__/prototypes/mulch")
require("__wayward-seas__/prototypes/excav_brace")
require("__wayward-seas__/prototypes/prod_research")
require("__wayward-seas__/prototypes/resin")